{{- if .Values.minio.deploy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ include "ai-gateway.namespace" . }}
  labels: {{- include "ai-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.secretKey | quote }}
{{- end }}
