{{- if .Values.logCollector.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: log-collector-secret
  namespace: {{ include "ai-gateway.namespace" . }}
  labels: {{- include "ai-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@postgres:5432/chat_log" .Values.postgres.auth.username .Values.postgres.auth.password | quote }}
{{- end }}
