{{- if .Values.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: {{ include "ai-gateway.namespace" . }}
  labels: {{- include "ai-gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.kong.service.nodePort.enabled }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector: {{- include "ai-gateway.selectorLabels" (dict "root" . "name" "kong") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      {{- if .Values.kong.service.nodePort.enabled }}
      nodePort: {{ .Values.kong.service.nodePort.httpPort }}
      {{- end }}
    - name: https
      port: 8443
      targetPort: https
      {{- if .Values.kong.service.nodePort.enabled }}
      nodePort: {{ .Values.kong.service.nodePort.httpsPort }}
      {{- end }}
{{- end }}
